### ISSUE TITLE
Can not decode a recorded signal from nanocom ax100 transciever

### ISSUE THREAD

**Issue by mkamel27** [daniestevez/gr-satellites#265]
Hello,
I am trying to use gr-satellites to decode a recorded signal of a nanocom ax100 transceiver with no luck. I think the problem may be in the sync word, how can i change the syncword ? can i send you the file to decode ?

**Comment by daniestevez** [comment]
Dear Mohamed,

Could you please give us more information about how you're configuring the AX100 (it supports several modes of operation) and how you are are using gr-satellites to decode the signal?

The standard syncwords for the ASM+Golay and Reed-Solomon are hardcoded somewhere in the gr-satellites deframers, but I've never seen a satellite using a non-standard syncword, so perhaps this isn't the cause of your problem.

**Comment by daniestevez** [comment]
Those look like completely standard settings of the AX100 transceiver, and your flowgraph should be able to decode the frames.

There is something about the sync word that perhaps is worth mentioning (taken from [this post](https://destevez.net/2018/01/a-first-look-at-ty-2/) I wrote several years ago):

> [...] the manual gives the syncword as [0xC9D08A7B] MSB, but this is misleading. This is only correct if each byte is sent starting by the least significant bit, which is not the case for the length field and data.

So 0xC9D08A7B is the sync word in LSB first notation, which is counter-intuitive, since the AX100 sends all the data MSB first.

I can't see anything wrong with your flowgraph. I would typically decimate before going into the FSK demodulator, but it should work nevertheless. So this leaves signal quality aspects as possible causes of the problem.

**Comment by mkamel27** [comment]
Thank you for your reply. I will try again with a better recording.

**Comment by mkamel27** [comment]
Hello @daniestevez,
I tried a better recording and added bit slicer and a file sink after the fsk demodulator. I can find the 100 byte preamble of 0XAA but can not find the syncword. Any recommendation ?

**Comment by daniestevez** [comment]
Are the demodulated symbols clean and with no bit errors? See the [gr-satellites documentation](https://gr-satellites.readthedocs.io/en/latest/command_line.html#dump-internal-signals) for how to plot these with the command line tool, or just use a QT Time Sink as in `examples/components/fsk_demodulator.grc`.

**Comment by mkamel27** [comment]
![Screenshot from 2021-05-02 19-58-57](https://user-images.githubusercontent.com/16439399/116822783-1f592980-ab81-11eb-83f3-3d03eb86b9b6.png)
Here is the output of the fsk_demodulator.

**Comment by daniestevez** [comment]
That looks good, other than the fact that the frame seems quite short (should it be so short?). I haven't visually checked if the syncword is correct.

**Comment by mkamel27** [comment]
I think it should be short because the data is only 4 bytes. Is it possible to find the syncword ? Isn't the syncword scrambled ?

**Comment by daniestevez** [comment]
The syncword is not scrambled in ASM+Golay mode.

**Comment by mkamel27** [comment]
I am out of ideas, whateo you recommend ?

**Comment by daniestevez** [comment]
I recommend you look carefully at your Audacity screenshot, which is something that I haven't done. Try to find if the syncword is there. It should be
```
_syncword = '10010011000010110101000111011110'
```

Look at the Golay-encoded header following the syncword. Is it correct? Look at the rest of the data. Does it match the payload you intend to transmit?

**Comment by daniestevez** [comment]
Hi @mkamel27, any progress with this? Did you manage to check if anything in the waveform in Audacity resembles the data you intended to transmit?

**Comment by mkamel27** [comment]
Hello,
I could not extract the data using audacity so I dumped the binary data using gnuradio. I found the preamble but I could not find the payload or the syncword at all.

**Comment by daniestevez** [comment]
Then I don't know what your problem is. In the ASM+Golay mode the syncword is sent unencoded, so other than the weird endianness choice in the user manual that I mentioned above, you should be able to see it in plain sight. Maybe your clock recovery is wrong? Have you tried to do the same with the FSK demodulated waveform (before clock recovery)? The other possibility is that you AX100 is not correctly configured.

**Comment by mkamel27** [comment]
I have tried a custom fsk demodulation using gnuradio blocks with no luck. I also suspect the ax100 configuration. What do you think I should check in the configuration ?

**Comment by daniestevez** [comment]
No idea. I don't have any first hand experience with the configuration of the AX100. Maybe you can try to get GOMspace in the loop for some support?

**Comment by mkamel27** [comment]
I will try. Thanks for your support

**Comment by daniestevez** [comment]
@mkamel27 since this might be a configuration problem with the AX100, can we close this issue?

**Comment by mkamel27** [comment]
Yeah sure. Thanks though.
