### ISSUE TITLE
PyBombs recipe installs unsupported version of python construct

### ISSUE THREAD

**Issue by arcticspace** [daniestevez/gr-satellites#47]
Hi, when installing gr-satellites via pybombs I have seen that the apt-get packet manager is used to install python-construct. Unfortunately the ubuntu:latest repository does have a version which is working. I had to install construct via pip to solve the problem.

My suggestion: Replace apt-get install python-construct with pip install construct. I attached a screenshot. 

Best regards,

![image](https://user-images.githubusercontent.com/53013264/63585880-66b3a800-c5a0-11e9-9569-5c651c588163.png)

**Comment by daniestevez** [comment]
Thanks for the report. I don't use PyBOMBS or ubuntu, so I'm not sure why PyBOMBS uses apt-get instead of pip to install construct.

However, I have seen that the PyBOMBS recipe for construct referred to version 2.8. Since gr-satellite requires version 2.9, I have updated the recipe. I have submitted a [pull request](https://github.com/gnuradio/gr-etcetera/pull/75) with this.

Could you please test if the updated recipe solves your problem?

**Comment by arcticspace** [comment]
Will do once the pull request was done.

**Comment by daniestevez** [comment]
The pull request has now been merged.

**Comment by daniestevez** [comment]
I'm closing this, since I have checked that the recipe for pyconstruct uses version 2.9.45 if building from source, or >=2.9 if satisfied from other package manager.
