### ISSUE TITLE
3.8 - clone, download v3-alpha0.tar.gz, or both?

### ISSUE THREAD

**Issue by K4KDR** [daniestevez/gr-satellites#55]
I don't know if I did an unnecessary step or not.

To follow along with the development & testing of 3.8 gr-satellites, is it necessary (or even desirable) to clone the maint-3.8 branch with:

`git clone -b maint-3.8 --single-branch https://github.com/daniestevez/gr-satellites.git`

... or should that be skipped and only download manually the tar.gz releases when you announce that a new one is available?

Thanks!

**Comment by daniestevez** [comment]
Hi Scott,

First note that the development of gr-satellites v3 (the alphas, etc.) doesn't happen on the `maint-3.8` but rather on the `next` branch. The `maint-3.8` branch will be used to release stable versions for GNU Radio 3.8 following the old model we are used to, until the v3 refactor is released as a stable version.

Regarding whether it is best to follow `next` or to stick to the released alphas, I can't give a recommendation, as this depends on personal taste. For the alphas I will try to describe the new functionality that has been implemented and to test it so that it works more or less well. If you follow the `next` branch, you will track the progress of the refactor more closely, but things might be undocumented or not work.
